-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 09:18:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FinderDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FinderDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinderDB` DEFAULT CHARACTER SET utf8 ;
USE `FinderDB` ;

-- -----------------------------------------------------
-- Table `FinderDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`User` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT COMMENT 'Automatisch, numerisch aufsteigende Zahl die von der Datenbank selbst erstellt wird.\n\nPRIMARY KEY',
  `benutzername` VARCHAR(45) NOT NULL COMMENT 'Benutzername. Nicht null und einzigartig, da jeder Benutzer eindeutig identifiziert werden muss.',
  `vorname` VARCHAR(45) NOT NULL COMMENT 'Vorname des Benutzers',
  `nachname` VARCHAR(45) NOT NULL COMMENT 'Nachname des Benutzers',
  `geburtsdatum` DATE NOT NULL COMMENT 'Geburtsdatum - Pflichtfeld da gewisse Filme erst ab 18 einsichtbar sind.',
  `passwort` VARCHAR(100) NOT NULL COMMENT 'Passwort des Benutzers als Hashwert gespeichert.\n\nKEIN PASSWORT IN KLARSCHRIFT ABSPEICHERN!',
  `preference` VARCHAR(100) NULL,
  `userCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `userChanged` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUser_UNIQUE` ON `FinderDB`.`User` (`idUser` ASC);

CREATE UNIQUE INDEX `Benutzername_UNIQUE` ON `FinderDB`.`User` (`benutzername` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Genre` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `Genre` VARCHAR(50) NULL COMMENT 'Kurze Beschreibung des Genre (z.B. Action, Comedy, usw.)',
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idGenre_UNIQUE` ON `FinderDB`.`Genre` (`idGenre` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Keywords` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Keywords` (
  `idKeywords` INT NOT NULL AUTO_INCREMENT,
  `keywords` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKeywords`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idKeywords_UNIQUE` ON `FinderDB`.`Keywords` (`idKeywords` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Movie` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Movie` (
  `idMovie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `year` YEAR NOT NULL,
  `Genre` INT NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `language` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idMovie`),
  CONSTRAINT `fk_Movie_Genre`
    FOREIGN KEY (`Genre`)
    REFERENCES `FinderDB`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMovie_UNIQUE` ON `FinderDB`.`Movie` (`idMovie` ASC);

CREATE INDEX `fk_Movie_Genre_idx` ON `FinderDB`.`Movie` (`Genre` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Movie_has_Movies_Keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Movie_has_Movies_Keywords` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Movie_has_Movies_Keywords` (
  `Movie_idMovie` INT NOT NULL,
  `Movies_Keywords_idMovies_Keywords` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `Movies_Keywords_idMovies_Keywords`),
  CONSTRAINT `fk_Movie_has_Movies_Keywords_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `FinderDB`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Movie_has_Movies_Keywords_Movie1_idx` ON `FinderDB`.`Movie_has_Movies_Keywords` (`Movie_idMovie` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Movies_Keywords_has_Keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Movies_Keywords_has_Keywords` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Movies_Keywords_has_Keywords` (
  `Movies_Keywords_idMovies_Keywords` INT NOT NULL,
  `Keywords_idKeywords` INT NOT NULL,
  PRIMARY KEY (`Movies_Keywords_idMovies_Keywords`, `Keywords_idKeywords`),
  CONSTRAINT `fk_Movies_Keywords_has_Keywords_Keywords1`
    FOREIGN KEY (`Keywords_idKeywords`)
    REFERENCES `FinderDB`.`Keywords` (`idKeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Movies_Keywords_has_Keywords_Keywords1_idx` ON `FinderDB`.`Movies_Keywords_has_Keywords` (`Keywords_idKeywords` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Movie_has_Keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Movie_has_Keywords` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Movie_has_Keywords` (
  `Movie_idMovie` INT NOT NULL,
  `Keywords_idKeywords` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `Keywords_idKeywords`),
  CONSTRAINT `fk_Movie_has_Keywords_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `FinderDB`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Movie_has_Keywords_Movie1_idx` ON `FinderDB`.`Movie_has_Keywords` (`Movie_idMovie` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Movie_has_Keywords_has_Keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Movie_has_Keywords_has_Keywords` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Movie_has_Keywords_has_Keywords` (
  `Movie_has_Keywords_Movie_idMovie` INT NOT NULL,
  `Movie_has_Keywords_Keywords_idKeywords` INT NOT NULL,
  `Keywords_idKeywords` INT NOT NULL,
  PRIMARY KEY (`Movie_has_Keywords_Movie_idMovie`, `Movie_has_Keywords_Keywords_idKeywords`, `Keywords_idKeywords`),
  CONSTRAINT `fk_Movie_has_Keywords_has_Keywords_Movie_has_Keywords1`
    FOREIGN KEY (`Movie_has_Keywords_Movie_idMovie` , `Movie_has_Keywords_Keywords_idKeywords`)
    REFERENCES `FinderDB`.`Movie_has_Keywords` (`Movie_idMovie` , `Keywords_idKeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Keywords_has_Keywords_Keywords1`
    FOREIGN KEY (`Keywords_idKeywords`)
    REFERENCES `FinderDB`.`Keywords` (`idKeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Movie_has_Keywords_has_Keywords_Keywords1_idx` ON `FinderDB`.`Movie_has_Keywords_has_Keywords` (`Keywords_idKeywords` ASC);

CREATE INDEX `fk_Movie_has_Keywords_has_Keywords_Movie_has_Keywords1_idx` ON `FinderDB`.`Movie_has_Keywords_has_Keywords` (`Movie_has_Keywords_Movie_idMovie` ASC, `Movie_has_Keywords_Keywords_idKeywords` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Actor` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Actor` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `vorname` VARCHAR(255) NULL,
  `nachname` VARCHAR(255) NULL,
  `zweiterVorname` VARCHAR(255) NULL,
  `geschlecht` VARCHAR(45) NULL,
  `geburtstag` DATE NULL,
  PRIMARY KEY (`idActor`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idActor_UNIQUE` ON `FinderDB`.`Actor` (`idActor` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Movie_has_Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Movie_has_Actor` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Movie_has_Actor` (
  `Movie_idMovie` INT NOT NULL,
  `Actor_idActor` INT NOT NULL,
  `character` VARCHAR(255) NULL,
  PRIMARY KEY (`Movie_idMovie`, `Actor_idActor`),
  CONSTRAINT `fk_Movie_has_Actor_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `FinderDB`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Actor_Actor1`
    FOREIGN KEY (`Actor_idActor`)
    REFERENCES `FinderDB`.`Actor` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Movie_has_Actor_Actor1_idx` ON `FinderDB`.`Movie_has_Actor` (`Actor_idActor` ASC);

CREATE INDEX `fk_Movie_has_Actor_Movie1_idx` ON `FinderDB`.`Movie_has_Actor` (`Movie_idMovie` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Watchlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Watchlist` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Watchlist` (
  `Movie_idMovie` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `User_idUser`),
  CONSTRAINT `fk_Movie_has_User_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `FinderDB`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `FinderDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Movie_has_User_User1_idx` ON `FinderDB`.`Watchlist` (`User_idUser` ASC);

CREATE INDEX `fk_Movie_has_User_Movie1_idx` ON `FinderDB`.`Watchlist` (`Movie_idMovie` ASC);


-- -----------------------------------------------------
-- Table `FinderDB`.`Playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Playlist` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Playlist` (
  `User_idUser` INT NOT NULL,
  `playlistCreated` DATETIME NULL,
  PRIMARY KEY (`User_idUser`),
  CONSTRAINT `fk_Playlist_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `FinderDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinderDB`.`Playlist_has_movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinderDB`.`Playlist_has_movie` ;

CREATE TABLE IF NOT EXISTS `FinderDB`.`Playlist_has_movie` (
  `Movie_idMovie` INT NOT NULL,
  `Playlist_User_idUser` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `Playlist_User_idUser`),
  CONSTRAINT `fk_Movie_has_Playlist_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `FinderDB`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Playlist_Playlist1`
    FOREIGN KEY (`Playlist_User_idUser`)
    REFERENCES `FinderDB`.`Playlist` (`User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Movie_has_Playlist_Playlist1_idx` ON `FinderDB`.`Playlist_has_movie` (`Playlist_User_idUser` ASC);

CREATE INDEX `fk_Movie_has_Playlist_Movie1_idx` ON `FinderDB`.`Playlist_has_movie` (`Movie_idMovie` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
